// <auto-generated />
using System;
using Galaxy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Galaxy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260809114151_AddShipAssembly")]
    partial class AddShipAssembly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Galaxy.Domain.Entities.ComponentInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId", "ComponentCode")
                        .IsUnique();

                    b.ToTable("ComponentInventory");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ComponentProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId", "LineNumber", "QueuePosition")
                        .IsUnique();

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssemblyComplexLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BuildingCompletesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BuildingSiteCapacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Deuterium")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<int>("DeuteriumExtractorLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("Materials")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)");

                    b.Property<int>("MaterialsExtractorLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("PowerPlantLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionComplexLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("QueuedBuilding")
                        .HasColumnType("integer");

                    b.Property<int?>("QueuedBuildingLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ResearchLaboratoryLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ResourcesUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StarSystemId")
                        .HasColumnType("uuid");

                    b.Property<int>("WarehouseLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("StarSystemId", "Position")
                        .IsUnique();

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("QueuedTechnology")
                        .HasColumnType("integer");

                    b.Property<int?>("QueuedTechnologyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Race")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ResearchCompletesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.PlayerTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Technology")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Technology")
                        .IsUnique();

                    b.ToTable("PlayerTechnologies");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipBlueprintId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ShipBlueprintId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ShipAssemblyOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("QueuePosition")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShipBlueprintId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShipBlueprintId");

                    b.HasIndex("PlanetId", "QueuePosition")
                        .IsUnique();

                    b.ToTable("ShipAssemblyOrders");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ShipBlueprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HullCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("ShipBlueprints");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ShipBlueprintModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShipBlueprintId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShipBlueprintId", "ComponentCode")
                        .IsUnique();

                    b.ToTable("ShipBlueprintModules");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.StarSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GalaxyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SystemNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GalaxyNumber", "SystemNumber")
                        .IsUnique();

                    b.ToTable("StarSystems");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ComponentInventoryItem", b =>
                {
                    b.HasOne("Galaxy.Domain.Entities.Planet", "Planet")
                        .WithMany("ComponentInventory")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ComponentProductionOrder", b =>
                {
                    b.HasOne("Galaxy.Domain.Entities.Planet", "Planet")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.Planet", b =>
                {
                    b.HasOne("Galaxy.Domain.Entities.Player", "Player")
                        .WithMany("Planets")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Galaxy.Domain.Entities.StarSystem", "StarSystem")
                        .WithMany("Planets")
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("StarSystem");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.PlayerTechnology", b =>
                {
                    b.HasOne("Galaxy.Domain.Entities.Player", "Player")
                        .WithMany("Technologies")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.Ship", b =>
                {
                    b.HasOne("Galaxy.Domain.Entities.Planet", "Planet")
                        .WithMany("Ships")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Galaxy.Domain.Entities.Player", "Player")
                        .WithMany("Ships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Galaxy.Domain.Entities.ShipBlueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("ShipBlueprintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Planet");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ShipAssemblyOrder", b =>
                {
                    b.HasOne("Galaxy.Domain.Entities.Planet", "Planet")
                        .WithMany("AssemblyOrders")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Galaxy.Domain.Entities.ShipBlueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("ShipBlueprintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ShipBlueprint", b =>
                {
                    b.HasOne("Galaxy.Domain.Entities.Player", "Player")
                        .WithMany("Blueprints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ShipBlueprintModule", b =>
                {
                    b.HasOne("Galaxy.Domain.Entities.ShipBlueprint", "ShipBlueprint")
                        .WithMany("Modules")
                        .HasForeignKey("ShipBlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipBlueprint");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.Planet", b =>
                {
                    b.Navigation("AssemblyOrders");

                    b.Navigation("ComponentInventory");

                    b.Navigation("ProductionOrders");

                    b.Navigation("Ships");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.Player", b =>
                {
                    b.Navigation("Blueprints");

                    b.Navigation("Planets");

                    b.Navigation("Ships");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.ShipBlueprint", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Galaxy.Domain.Entities.StarSystem", b =>
                {
                    b.Navigation("Planets");
                });
#pragma warning restore 612, 618
        }
    }
}
